# Generated by Django 3.2.25 on 2024-10-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
